function alib(ch)

path_own = ...
    { ...
        fullfile('..','include','classes') , ...
        fullfile('..','include','functions') ...
    };
    
switch lower(ch)

    case 1
	pathSetter(...
            '.' , 1 , ...
            path_own ...
            );
            
    case 2
        pathSetter(...
            '.' , 2 , ...
            path_own ...
            );
            
    otherwise
	  warning('MATLAB:NoSwitchCase','Nothing to do in path setting.');
end
